<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * @file
 * Module file for iFrame module
 */

/**
 * Implements hook_theme().
 */
function farm_iframe_theme() {
  return array(
    'farm_iframe_panel_formatter' => array(
      'variables' => array('url' => NULL),
    ),
    'farm_iframe_full_view_1' => array(
      'variables' => array('url' => NULL),
    ),
  );
}

/**
 * Implements hook_entity_base_field_info().
 */
function farm_iframe_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'asset') {
    $fields['iframe_panel_link'] = BaseFieldDefinition::create('iframe')
    ->setLabel(t('iFrame Panel'))
    ->setDescription(t('Option to add an iFrame Panel'))
    ->setRevisionable(TRUE);

    $fields['iframe_panel_link']->setDisplayOptions('form', [
      'type' => 'options_buttons',
      'weight' => $options['weight']['form'] ?? 0,
    ]);

    $fields['iframe_panel_link']->setDisplayOptions('view', [
      'label' => 'inline',
      'type' => 'list_default',
      'weight' => $options['weight']['view'] ?? 0,
    ]);

    return $fields;
 }
}


