# Schema for the configuration files of the iframe module.
farm_iframe.settings:
  type: config_object
  label: 'iframe Settings'
  mapping:
    iframe_1_url:
      type: string
      label: 'Iframe 1 Url'

