# Schema for the configuration files of the iframe module.
farm_iframe.settings:
  type: config_object
  label: 'iframe Settings'
  mapping:
    iframe1:
      type: string
      label: 'Iframe 1 Url'
    iframe2:
      type: string
      label: 'Iframe 2 Url'
    iframe3:
      type: string
      label: 'Iframe 3 Url'
    iframe4:
      type: string
      label: 'Iframe 4 Url'